language: php
dist: precise

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - master

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

before_script:
  - echo "memory_limit=2G" >> $HOME/.phpenv/versions/`phpenv version-name`/etc/conf.d/travis.ni
  - phpize && ./configure && make

script:
  - make test TESTS="--show-diff" | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null ; test $? '!=' 0

after_failure:
  - for FILE in `find ./tests -name '*.diff'`; do echo echo $FILE; cat $FILE; echo; done
